version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: "/myapp/docker-credentials/username"
    DOCKER_PASSWORD: "/myapp/docker-credentials/password"
    DOCKER_REGISTRY_URL: "/myapp/docker-registry/url"

  variables:
    IMAGE_REPO_NAME: "test-node-app"
    IMAGE_NAME: "$DOCKER_USERNAME/test-node-app"

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - echo "Logging in to DockerHub..."
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

  build:
    commands:
      - echo "Building Docker image..."
      - docker build -t $IMAGE_NAME:latest .
      - echo "Creating zip package..."
      - zip -r test-node-app.zip * .[^.]*

  post_build:
    commands:
      - echo "Pushing Docker image to DockerHub..."
      - docker push $IMAGE_NAME:latest
      - echo "Uploading zip file to S3..."
      - aws s3 cp test-node-app.zip s3://new-test-bucket-122/test-node-app/
      - echo "Uploaded zip file to S3."
      - echo "Writing image definitions file..."
      - printf '{"ImageURI":"%s", "Port":8000}' $IMAGE_NAME:latest > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - '**/*'
    - test-node-app.zip 
  base-directory: '.'
  discard-paths: no
  exclude-patterns:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'
