version: 0.2

env:
  parameter-store:
    DOCKER_USERNAME: /myapp/docker-credentials/username
    DOCKER_PASSWORD: /myapp/docker-credentials/password
  variables:
    REPOSITORY_NAME: maverick334/test-node-app

phases:
  install:
    runtime-versions:
      nodejs: 12.2.0

  pre_build:
    commands:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - if [[ $? -eq 0 ]]; then echo "Docker login successful"; else echo "Docker login failed"; exit 1; fi
      - export IMAGE_URI="$DOCKER_USERNAME/$REPOSITORY_NAME" # Define the full image URI here
      - echo "Image URI: $IMAGE_URI" # Important for debugging

  build:
    commands:
      - docker build -t $IMAGE_URI:latest . # Use $IMAGE_URI here!

  post_build:
    commands:
      - docker push $IMAGE_URI:latest # Use $IMAGE_URI here!
      - echo Uploading zip file to S3 root location...
      - aws s3 cp node-todo-app.zip s3://tws-aws-cicd-demo/node-todo-app/ # Upload zip file to the root of the bucket
      - echo Writing image definitions file...
      - printf '{"ImageURI":"%s", "Port":8000}' $IMAGE_NAME:latest > imageDefinitions.json
      - cat imageDefinitions.json

artifacts:
  files:
    - '**/*'
  base-directory: '.'
  discard-paths: no
  exclude-patterns:
    - 'node_modules/**/*'
    - '.git/**/*'
    - '.gitignore'
    - 'README.md'
    - 'package-lock.json'


